<?php

namespace App\DocumentEngine\Templates;

use App\Models\DocumentTemplate;

class DocumentTemplateRegistry
{
    public static function seedDefaultTemplates(int $companyId, ?int $branchId = null): void
    {
        $templates = [
            [
                'document_type' => 'SALES_INVOICE',
                'template_key' => 'classic_gst',
                'template_name' => 'Standard Indian GST Tax Invoice',
                'paper_size' => 'A4',
                'orientation' => 'PORTRAIT',
                'brand_color' => '#1e3a8a',
                'accent_color' => '#3b82f6',
                'font_family' => 'Inter, sans-serif',
                'logo_position' => 'LEFT',
                'watermark_enabled' => false,
                'watermark_text' => null,
                'show_bank_details' => true,
                'show_upi_qr' => true,
                'show_signature' => true,
                'show_stamp' => false,
                'show_hsn_summary' => true,
                'show_tax_breakdown' => true,
                'show_amount_in_words' => true,
                'show_terms' => true,
                'default_terms' => "1. Goods once sold will not be taken back.\n2. Interest @ 18% p.a. will be charged if payment is not made within credit period.\n3. Subject to local jurisdiction only.",
                'default_notes' => 'Thank you for your business!',
                'is_default' => true,
                'is_system' => true,
            ],
            [
                'document_type' => 'SALES_INVOICE',
                'template_key' => 'modern_gst',
                'template_name' => 'Modern Royal Blue Invoice',
                'paper_size' => 'A4',
                'orientation' => 'PORTRAIT',
                'brand_color' => '#2563eb',
                'accent_color' => '#60a5fa',
                'font_family' => 'Inter, sans-serif',
                'logo_position' => 'LEFT',
                'watermark_enabled' => false,
                'watermark_text' => null,
                'show_bank_details' => true,
                'show_upi_qr' => true,
                'show_signature' => true,
                'show_stamp' => false,
                'show_hsn_summary' => true,
                'show_tax_breakdown' => true,
                'show_amount_in_words' => true,
                'show_terms' => true,
                'default_terms' => 'Payment due within 30 days of invoice date.',
                'default_notes' => 'We appreciate your prompt payment.',
                'is_default' => false,
                'is_system' => true,
            ],
            [
                'document_type' => 'SALES_INVOICE',
                'template_key' => 'thermal_80mm',
                'template_name' => '80mm POS Thermal Receipt',
                'paper_size' => 'THERMAL_80MM',
                'orientation' => 'PORTRAIT',
                'brand_color' => '#000000',
                'accent_color' => '#000000',
                'font_family' => 'Courier New, monospace',
                'logo_position' => 'CENTER',
                'watermark_enabled' => false,
                'watermark_text' => null,
                'show_bank_details' => false,
                'show_upi_qr' => false,
                'show_signature' => false,
                'show_stamp' => false,
                'show_hsn_summary' => false,
                'show_tax_breakdown' => true,
                'show_amount_in_words' => false,
                'show_terms' => false,
                'default_terms' => null,
                'default_notes' => 'Thank you for shopping with us!',
                'is_default' => false,
                'is_system' => true,
            ],
            [
                'document_type' => 'QUOTATION',
                'template_key' => 'quotation_classic',
                'template_name' => 'Standard Quotation / Estimate',
                'paper_size' => 'A4',
                'orientation' => 'PORTRAIT',
                'brand_color' => '#0f766e',
                'accent_color' => '#14b8a6',
                'font_family' => 'Inter, sans-serif',
                'logo_position' => 'LEFT',
                'watermark_enabled' => true,
                'watermark_text' => 'ESTIMATE / QUOTATION',
                'show_bank_details' => false,
                'show_upi_qr' => false,
                'show_signature' => true,
                'show_stamp' => false,
                'show_hsn_summary' => true,
                'show_tax_breakdown' => true,
                'show_amount_in_words' => true,
                'show_terms' => true,
                'default_terms' => "1. Quotation valid for 30 days.\n2. Taxes and duties as applicable at the time of delivery.\n3. Delivery within 7 working days from purchase order.",
                'default_notes' => 'Please contact us if you have any questions.',
                'is_default' => true,
                'is_system' => true,
            ],
            [
                'document_type' => 'CUSTOMER_STATEMENT',
                'template_key' => 'statement_classic',
                'template_name' => 'Standard Ledger Statement',
                'paper_size' => 'A4',
                'orientation' => 'PORTRAIT',
                'brand_color' => '#374151',
                'accent_color' => '#4b5563',
                'font_family' => 'Inter, sans-serif',
                'logo_position' => 'LEFT',
                'watermark_enabled' => false,
                'watermark_text' => null,
                'show_bank_details' => true,
                'show_upi_qr' => false,
                'show_signature' => true,
                'show_stamp' => false,
                'show_hsn_summary' => false,
                'show_tax_breakdown' => false,
                'show_amount_in_words' => true,
                'show_terms' => false,
                'default_terms' => null,
                'default_notes' => 'Please verify the statement and report any discrepancies within 7 days.',
                'is_default' => true,
                'is_system' => true,
            ],
        ];

        foreach ($templates as $tmpl) {
            DocumentTemplate::firstOrCreate(
                [
                    'company_id' => $companyId,
                    'document_type' => $tmpl['document_type'],
                    'template_key' => $tmpl['template_key'],
                ],
                array_merge($tmpl, [
                    'branch_id' => $branchId,
                    'version' => 1,
                ])
            );
        }
    }
}
